{{- if and .Values.httproute .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "backend-go.fullname" . }}
  labels:
    {{- include "backend-go.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httproute.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.httproute.hostnames | nindent 4 }}
  rules:
    {{- range .Values.httproute.rules }}
    - matches:
        - path:
            type: {{ .path.type | default "PathPrefix" }}
            value: {{ .path.value }}
      {{- with .timeouts }}
      timeouts:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      backendRefs:
        - name: {{ include "backend-go.fullname" $ }}
          port: {{ $.Values.service.api.port }}
    {{- end }}
{{- end }}
